#!/bin/bash

## After Boot

checkReq(){

	REQS=('modprobe' 'lsmod' 'swapon' 'mkswap' 'zramctl' )

	for REQ in ${REQS[@]}; do
		if ! command -v $REQ>/dev/null; then
			echo "$REQ not installed on this system!"
			exit 1
		fi
	done


}

checkPriv(){

	if [[ $EUID -ne '0' ]]; then
		echo 'Run me as root!'
		exit 1
	fi

}

zramOn(){

	ZRAM_SIZE='4G'
	ZRAM_FILE='/dev/zram0'

	if [[ $(swapon -s) != '' ]]; then
		echo 'Swap already on!'
		return
	fi

	if ! lsmod | grep ^zram 1>/dev/null; then
		modprobe zram
	fi

	mkSwap(){
		zramctl $ZRAM_FILE --algorithm zstd --size $ZRAM_SIZE
		mkswap -U clear $ZRAM_FILE
		swapon --priority 100 $ZRAM_FILE
	}

	mkSwap 1>/dev/null
}

reniceProc(){

	procs=( 'pipewire-pulse' 'wireplumber' 'pasystray' 'pulseaudio' )

	for proc in "${procs[@]}"; do
		if pidof $proc 1>/dev/null; then
			renice -20 $(pidof $proc)
		else
			continue
		fi
	done


}

enableNouveau(){

	if ! lsmod|grep ^nouveau 1>/dev/null; then
		modprobe nouveau
		if pidof Xorg>/dev/null; then
			echo 'Close everything and press: [enter]'
			read && killall Xorg
		else
			echo 'Xorg is not running!'
			continue
		fi
	else
		echo 'Nouveau already enabled'
		return
	fi

}

main(){

	checkPriv
	zramOn
	reniceProc
	enableNouveau

}

main
