#!/bin/bash

set -euo pipefail

compositor=picom

if [ -z $XAUTHORITY ]; then
	exit 1
fi

if ! pidof Xorg>/dev/null; then
	exit 1
fi

if pidof $compositor>/dev/null; then
	killall $compositor
else
	coproc $compositor
	renice -20 $(pidof $compositor)
fi

xrefresh
