#!/bin/bash
## Select an emoji and copy it to the clipboard.
set -euxo pipefail

DMENU='rofi -dmenu -i -p'
EMOJI_FILE="${HOME}/.emoji"

EMOJI=$( ${DMENU} "🔎 Search for emoji: " < "${EMOJI_FILE}" | awk '{print $1}')
echo -n "${EMOJI}" | xclip -selection clipboard

if [[ "${EMOJI}" ]]; then
	notify-send -u low "${EMOJI} Emoji copied to clipboard!"
fi
