#!/bin/bash

## Edit a Tempfile

RED='\e[31m' RC='\e[0m'

if [[ -z $EDITOR ]]; then
	echo "No editor found!"
	exit 1
fi

MKTEMP='mktemp'
REQS=("$EDITOR" "$MKTEMP")
for REQ in "${REQS[@]}"; do
	if ! command -v "${REQ}" >/dev/null; then
		echo -e "${RED}To run me, you need: ${REQ}${RC}"
		exit 1
	fi
done

$EDITOR "$($MKTEMP)"
