#!/usr/bin/env bash
## Free up system cache

USER_HOME=$(find /home -maxdepth 1|grep -v '^/home$'|head -n1)

removeCache() {

	CACHE_DIRS=( '.cache' '.mozilla' '.config/Binance/Partitions/binance.app/Cache' '.config/molotov/Cache' '.local/share/TelegramDesktop/tdata/temp' )

	for CACHE_DIR in ${CACHE_DIRS[@]}; do

		CACHE_DIR="${USER_HOME}/${CACHE_DIR}"

		[[ -d ${CACHE_DIR} ]] && rm -fr ${CACHE_DIR}&

	done

}

emptySwap() {

	sync
	swapoff -a
	swapon -a
	echo 3>/proc/sys/vm/drop_caches

}


main() {

	[[ ${EUID} -ne '0' ]] && { echo -e 'Run me as root!'; exit 1; }

	removeCache && echo "Cache removed!"

	if swapon --show>/dev/null; then

		emptySwap && echo 'Swap has been emptied!'

	fi
}

main || { echo 'Something went wrong!'; exit 1; }
