#!/bin/bash

declare -gri oc_max_freq='4100000'	## Specify max freq manually (for overclocked cpu).
declare -gri floating_point='3'		## Precision (1-6).

setGovernorIcon() {

	case $scaling_governor in
	'schedutil')
		scaling_governor_icon='💡';;
	'userspace')
		scaling_governor_icon='🍷';;
	'performance')
		scaling_governor_icon='⛽️';;
	'powersave')
		scaling_governor_icon='🌱';;
	'ondemand')
		scaling_governor_icon='🎢';;
	'conservative')
		scaling_governor_icon='🧘';;
	*)
		scaling_governor_icon='❓';;
	esac

}

setRatioColorIcon() {

	local -ri _scaled_ratio=$1

	case 1 in
	$((_scaled_ratio > 101)))
		color='\e[7m\e[1m\e[35m'; icon='🦄';;
	$((_scaled_ratio >= 80)))
		color='\e[7m\e[1m\e[31m'; icon='🐆';;
	$((_scaled_ratio >= 50)))
		color='\e[7m\e[1m\e[33m'; icon='🐇';;
	$((_scaled_ratio >= 40)))
		color='\e[7m\e[1m\e[32m'; icon='🐢';;
	$((_scaled_ratio >= 30)))
		color='\e[7m\e[1m\e[37m'; icon='🐌';;
	*)
		color='\e[7m\e[1m\e[38m'; icon='❓';;
	esac

}

getCoreNum(){

	declare -gi core_num
	core_num=$(nproc)

	declare -gi _core_num
	_core_num=$((core_num - 1))

}

getDriverGovernor() {

	## Read from cpu0, assuming all core have the same governor.
	declare -gr cpu_base_path="/sys/devices/system/cpu"
	declare -gr cpu_device_path="$cpu_base_path/cpu0/cpufreq"

	read -r scaling_governor <$cpu_device_path/scaling_governor
	read -r scaling_driver <$cpu_device_path/scaling_driver

	## Show icons too.
#	setGovernorIcon
#	echo -e " \e[4m$scaling_driver:\e[0m \e[1m$scaling_governor$scaling_governor_icon\e[0m\n"

	echo -e "  \e[4m\e[4mDriver\e[0m:\t\e[1m\e[7m$scaling_driver\e[0m
  \e[4mGovernor\e[0m:\t\e[1m\e[7m$scaling_governor\e[0m\n"



}

showCpuFreq() {


	for ((core = 0; core <= _core_num; core++)); do

		_cpu_device_path="$cpu_base_path/cpu$core/cpufreq"
		read -r scaling_cur_freq <$_cpu_device_path/scaling_cur_freq
		read -r scaling_max_freq <$_cpu_device_path/scaling_max_freq

		[[ -n $oc_max_freq ]] && scaling_max_freq=$oc_max_freq

		local freq_ghz; freq_ghz=$(bc <<< "scale=$floating_point; $scaling_cur_freq / 1000000")
		local scaling_ratio; scaling_ratio=$(bc <<< "scale=$floating_point; $scaling_cur_freq / $scaling_max_freq")

		[[ ${scaling_ratio:0:1} == '.' ]] && { local scaling_ratio; scaling_ratio="0$scaling_ratio"; }

		local scaled_ratio; scaled_ratio=$(bc <<< "$scaling_ratio * 100")
		local _scaled_ratio; _scaled_ratio=$(cut -d '.' -f 1 <<< "$scaled_ratio")

		setRatioColorIcon "$_scaled_ratio"

		local -i _core; _core=$((core + 1))

		echo -e " |-------+-----------+---------|\n | \e[4mcore$_core\e[0m | $color$freq_ghz\e[0m GHz | \e[2m($scaling_ratio)\e[0m |"

	done
}

main() {
	getCoreNum
	getDriverGovernor
	showCpuFreq
	echo -e " |-------+-----------+---------|"
}

main
