#!/bin/bash
## See: https://docs.docker.com/engine/install/debian/

set -euxo pipefail

if [[ ${EUID} -ne '0' ]]; then
	echo 'run me as root!'
fi

pkg_to_remove=(docker.io docker-doc docker-compose podman-docker containerd runc)
for pkg in "${pkg_to_remove[@]}"; do
	apt-get remove "${pkg}"
done

requirements=(ca-certificates curl gnupg)
apt-get update
apt-get install "${requirements[@]}"

install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

echo \
	"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
	$(. /etc/os-release && echo ${VERSION_CODENAME}) stable" \
	| tee /etc/apt/sources.list.d/docker.list >/dev/null

docker_pkgs=(docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin)
apt-get update
apt-get install "${docker_pkgs[@]}"

if docker run hello-world; then
	echo '\e[32mdocker installation complete!'
else
	echo '\e[31mdocker installation failed!'
	exit 1
fi
