#!/bin/bash

set -euo pipefail

warning_percent='60'

mem_usage_mb=$(free --mega |grep 'Mem' | awk '{print $2}')
mem_free_mb=$(free --mega |grep 'Mem' | awk '{print $3}')

usage_ratio=$(echo "${mem_free_mb}" / "${mem_usage_mb}" | bc -l)
usage_ratio_num=$(echo "${usage_ratio}"|tr -d '.')

usage_percent=${usage_ratio_num:0:2}

if [ "${usage_percent}" -gt "${warning_percent}" ]; then

	warning_logo='⚠️'
	echo -e "${warning_logo}"

fi
