#!/usr/bin/env bash
## Metasploit framework launcher.

## A launcher is needed since you can't background a session.
## (Ctrl+Z background the shell process instead)

## Disable Ctrl-Z
trap "" TSTP
msfconsole
