#!/usr/bin/env bash

## Metasploit framework launcher.

## A launcher is needed since you can't background a session (Ctrl+Z background the shell process instead)
## And Ctrl+C disconnect the database

trap '' TSTP
#trap '' SIGINT

msfconsole -Lan
