#!/bin/bash

## Optical Character Recognition.

set -euxo pipefail

SCREENSHOOTER='xfce4-screenshooter'
SCREENSHOOTER_OUTPUT="/tmp/${RANDOM}"
SCREENSHOOTER_DELAY='1'
SCREENSHOOTER_CMD="${SCREENSHOOTER} -r -d ${SCREENSHOOTER_DELAY} -s ${SCREENSHOOTER_OUTPUT}"
OCR_OUTPUT="/tmp/${RANDOM}"


takeScreenshoot(){

	if ! command -v "${SCREENSHOOTER}">/dev/null; then

		echo "${SCREENSHOOTER} not found!"
		exit 1

	fi

	${SCREENSHOOTER_CMD}

}

takeScreenshoot || exit 1


performOcr() {

	if ! command -v tesseract>/dev/null; then

		echo "Tesseract not found!"
		exit 1

	fi

	if [[ -e "${SCREENSHOOTER_OUTPUT}" ]]; then

		tesseract "${SCREENSHOOTER_OUTPUT}" "${OCR_OUTPUT}"

	else

		exit 1

	fi

}

performOcr


displayResult() {

	if [[ -e "${OCR_OUTPUT}.txt" ]]; then

		notify-send "$( cat ${OCR_OUTPUT}.txt )"

	else

		exit 1

	fi

}

displayResult
