#!/bin/bash
# Optical Character Recognition.

REQUIREMENTS=("tesseract" "xfce4-screenshooter" "xclip")
COMPOSITOR='picom'
OCR_OUTPUT="/tmp/ocr_${RANDOM}"
SCREENSHOT_OUTFILE="/tmp/screenshot_${RANDOM}"

# Check for required commands
for REQ in "${REQUIREMENTS[@]}"; do
  if ! command -v "${REQ}" >/dev/null 2>&1; then
    echo "${REQ} not found!"
    exit 1
  fi
done

# Check if compositor is running and kill it if necessary
COMPOSITOR_PID=$(pidof "${COMPOSITOR}")
if [[ -n "${COMPOSITOR_PID}" ]]; then
  echo "Killing compositor to prevent blur during screenshot..."
  kill "${COMPOSITOR_PID}"
  COMPOSITOR_WAS_RUNNING='0'
fi

# Take screenshot
xfce4-screenshooter -r -s "${SCREENSHOT_OUTFILE}"

# Restart compositor if it was running
[[ "${COMPOSITOR_WAS_RUNNING}" -eq '0' ]] && "${COMPOSITOR}" &
[[ ! -e "${SCREENSHOT_OUTFILE}" ]] && exit 1

# Perform OCR
tesseract "${SCREENSHOT_OUTFILE}" "${OCR_OUTPUT}" || exit 1

# Read OCR output
OCR_TEXT=$(<"${OCR_OUTPUT}.txt")
[[ -z "${OCR_TEXT}" ]] && exit 1

# Show OCR text in notification and copy to clipboard
APPNAME="${0}"
notify-send -a "${APPNAME}" "${OCR_TEXT}$(echo -e '\n\n📋 String copied to clipboard!')"
echo "${OCR_TEXT}" | xclip -selection clipboard

# Cleanup temporary files
rm -vfr "${SCREENSHOT_OUTFILE}" "${OCR_OUTPUT}.txt"
