#!/bin/bash

total_ram=$(free -m | awk '/Mem:/ {print $2}')
available_ram=$(free -m | awk '/Mem:/ {print $7}')

echo "Total RAM: $total_ram MB"
echo "Available RAM: $available_ram MB"

ram_used=$((100 - available_ram * 100 / total_ram))

case $ram_used_percent in
  [0-24]*)
    echo 🟢
    ;;
  [2-4][0-9]*)
    echo 🟡
    ;;
  [5-6][0-6]*)
    echo 🟠
    ;;
  6[7-9]|[7-9][0-9]|100)
    echo 🔴
    ;;
esac

