#!/bin/bash
set -euo pipefail


NIGHT_TIME='22'
DAY_TIME='6'
C_HOUR=$(date "+%H")

isItNight(){

	if [[ "${C_HOUR}" -le "${NIGHT_TIME}" && "${C_HOUR}" -gt "${DAY_TIME}" ]]; then
		W_TYPE='\-l'
		echo "🌇 It's day time, searching for a light background..."
	else
		W_TYPE='\-d'
		echo "🌃 It's night time, searching for a dark background..."
	fi

}

findBackground(){

	C_BACKGROUND=$(cat ~/.fehbg | awk '{print $4}' | tr -d "'\n" )

	IMG_TYPE='.svg|.png|.jpg|.jpeg'
	IMG_PATH='/usr/share/backgrounds/gnome/'

	if [ ! -d "${IMG_PATH}" ]; then
		echo "${IMG_PATH} not found!"
		exit 1
	fi


	RANDOM_BG=$(
		find -O3 -L "${IMG_PATH}" \
			| grep -E "${IMG_TYPE}" \
			| shuf \
			| grep "${W_TYPE}" \
			| grep -v "${C_BACKGROUND}" \
			| head -n1
	)

}


setBackground(){

	#feh --no-xinerama --bg-fill "${RANDOM_BG}" ## span accross multiple screens
	feh --bg-fill "${RANDOM_BG}"

}

main(){

	if isItNight; then
		if findBackground; then
			if setBackground; then
				exit 0
			fi

		fi
	fi

}

main
