#!/bin/bash
set -euo pipefail

# IMG_PATH="/usr/share/backgrounds/gnome"
IMG_PATH="${HOME}/Pictures/Wallpapers/Chrome OS Wallpapers/"
FILE_TYPE='.png|.jpg|.jpeg'

RANDOM_BG=$(find "${IMG_PATH}" -type f|grep -E "${FILE_TYPE}"|shuf|head -n1)

#feh --no-xinerama --bg-fill "${RANDOM_BG}"
feh --bg-fill "${RANDOM_BG}"
