#!/bin/bash
## Select CPU frequency gov on linux using acpi-cpufreq

checkRoot() {

	if [[ ${EUID} -ne '0' ]]; then
		echo -e "${WARN}Run me as root!${RC}"
		exit 1
	fi

}

setFreq(){

	ncpu=$(( $(nproc) - 1 ))
	dmenu_cmd='rofi -dmenu'

	gov_banned='userspace'
	gov_available=( $(cpufreq-info | grep "available cpufreq"|sort -u|cut -d ":" -f 2|tr -d " ") )
	gov_emojis=('⏲ schedutil' '🔌 performance' '🔋 powersave' '🔄 ondemand' '🐢 conservative')
	gov_selected=$( printf '%s\n' "${gov_emojis[@]}" | grep -v $gov_banned | $dmenu_cmd -p 'select governor:')

	[[ -z $gov_selected ]] && exit 1

	gov_name=$(echo $gov_selected | cut -d' ' -f2)

	for cpu in $(seq 0 $ncpu); do
		cpufreq-set -g $gov_name -c $cpu
	done

	case $gov_name in
		'schedutil')
			gov_icon='⏲';;
		'performance')
			gov_icon='🔌';;
		'powersave')
			gov_icon='🔋';;
		'ondemand')
			gov_icon='🔄';;
		'conservative')
			gov_icon='🐢';;
	esac

	notify-send "$gov_icon CPU is now using the $gov_name governor."
}

main(){

	if ! checkRoot; then
		exit 1
	fi

	setFreq

}

main
