#!/bin/bash
## Search on the web.
## Bind this script to a shortcut!

RED='\e[31m' RC='\e[0m'

BROWSER='firefox' DMENU='rofi'
REQUIREMENTS=( "${BROWSER}" "${DMENU}" )

for REQUIREMENT in "${REQUIREMENTS[@]}"; do
	if ! command -v "${REQUIREMENT}">/dev/null; then
		echo -e "${RED}To run me, you need: ${REQUIREMENT}${RC}"
		exit 1
	fi
done

DMENU_CMD='rofi -dmenu'
SEARCH_QUERY=$( ${DMENU_CMD} -p 'Search: ' )
[[ -z ${SEARCH_QUERY} ]] && exit 1

SEARCH_ENGINE[1]='google'
SEARCH_ENGINE[2]='youtube'
SEARCH_ENGINE[3]='github'
#SEARCH_ENGINE[3]='X'

SEARCH_ON=$(printf "%s\n" "${SEARCH_ENGINE[@]^}"|${DMENU_CMD} -p 'Search on: ')

[[ -z "${SEARCH_ON}" ]] &&  exit 1

case ${SEARCH_ON} in
	'Youtube'|'Google'|'Github')
		SEARCH_URL="https://www.${SEARCH_ON}.com/search?q=${SEARCH_QUERY}";;

	?|*)
		;;
esac

[[ "${BROWSER}" == 'firefox' || "${BROWSER}" == 'chromium' ]] && BROWSER_CMD="${BROWSER} --new-window"
[[ "${SEARCH_ON}" == 'Youtube' && "${BROWSER}" == 'firefox' ]] && BROWSER_CMD="${BROWSER_CMD} --private-window"

${BROWSER_CMD} "${SEARCH_URL}"&
