#!/bin/bash

temp_crit=$( sensors | grep 'crit' | awk '{print $9}' | cut -d '.' -f 1 | sort -u | tac | tr -d '+' | head -n 1 )
threshold=$(( "${temp_crit}" / 2 ))
sensor='temp1'

temp=$( sensors | grep "${sensor}" | awk {'print $2'} | tr -d '+' | cut -d '.' -f 1 )

if [ "${temp}" -gt "${threshold}" ]; then

	echo '🌡'

else

	echo -e " "

fi
