#!/bin/bash
set -eo pipefail

getTrend(){

	declare -Ir google_trends_country='FR'
	declare -Ir google_trends_url="https://trends.google.com/trends/trendingsearches/daily/rss?geo=${google_trends_country}"

	mapfile -t google_trends_results < <( curl -s "${google_trends_url}" | grep -oP '(?<=<title>).*(?=</title>)' | tail -n +2 )

	if [[ ! ${google_trends_results} ]];then
		notify-send -u critical -t 3000 "Can not get the latest trends!"
		exit 1
	fi

}

getTrend


selTrend(){

	local -Ir dmenu_cmd='rofi -dmenu -p Trends: '
	local -Ii n='0'

	google_trends_selected=$(\
		for google_trends_result in "${google_trends_results[@]}";do

			((n++));printf "${n} - %s\n" "${google_trends_result}"

		done|${dmenu_cmd}\
	)
}

selTrend


searchTrend(){

	x-www-browser "https://www.google.com/search?q=${google_trends_selected}"&disown
	exit 0

}

searchTrend
