#!/bin/bash

if ! command -v jgmenu>/dev/null;then
    exit 1
fi

if pidof jgmenu>/dev/null;then
    kill "$(pidof jgmenu)"
fi

lockfile="${HOME}/.jgmenu-lockfile"
if [ -e "${lockfile}" ];then
    rm "${lockfile}"
fi

jgmenu -simple --at-pointer&
