#!/bin/bash
ssh_pid=$(sudo pidof sshd)

if [ -n "${ssh_pid}" ]; then
	termux-toast "Killing ssh daemon ${ssh_pid}..."&
	kill ${ssh_pid}&&termux-toast "OK"&
else
	termux-toast "Starting SSH daemon..."&
	sshd&&termux-toast "OK"&
fi
